services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - modularize
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JSON_UPLOAD_DIRECTORY=./uploads/jsons

  frontend:
    build: ./frontend
    ports:
      - "3005:3005"
    networks:
      - modularize
    environment:
      - NODE_ENV=production

networks:
  modularize: